name:                hs-feserver
version:             0.1.0.0
github:              "diqye/hs-feserver"
license:             BSD3
author:              "diqye"
maintainer:          "262666212@qq.com"
copyright:           "copyright"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/diqye/hs-feserver#readme>

dependencies:
- warp-tls
- base >= 4.7 && < 5
- aeson
- binary
- appm
- scientific
- unordered-containers
- yaml
- text
- bytestring
- transformers
- directory
- http-client
- http-client-tls
- neat-interpolation
- filepath
- base64-bytestring
- http-types
- string-conversions
- io-streams

library:
  source-dirs: src

executables:
  hs-feserver-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: []

